-- Generated from scripts/palette/ithilien.json (ithilien-dusk); do not edit by hand.
return {
  colors = {
    ["Lebethron"] = "#000000",
    ["Cedar"] = "#AAA497",
    ["Briar"] = "#B8595C",
    ["Juniper"] = "#A6C995",
    ["Hyacinth"] = "#9DBDE0",
    ["Elanor"] = "#D0BD91",
    ["Tamarisk"] = "#C1B0CE",
    ["Cypress"] = "#273B31",
    ["Bramble"] = "#402E33",
    ["Morgulduin"] = "#293847",
    ["Celandine"] = "#D8B46A",
    ["Heather"] = "#D6C6DE",
    ["Ithil"] = "#BDB7AB",
    ["Arnen"] = "#2C2E2C",
    ["Morgai"] = "#303437",
    ["Duath"] = "#202120",
    ["Rose"] = "#E09A9D",
    ["Poros"] = "#83C9BE",
  },
  raw = {
    ["colorSpace"] = "sRGB",
    ["name"] = "Ithilien Dusk",
    ["slug"] = "ithilien-dusk",
    ["polarity"] = "dark",
    ["highlight"] = {
      ["background"] = "#B8595C",
      ["foreground"] = "#000000",
      ["border"] = "#AAA497",
      ["cursor"] = "#B8595C",
      ["cursorBlock"] = "#B8595C",
    },
    ["backgrounds"] = {
      ["crust"] = "#202120",
      ["mantle"] = "#303437",
      ["base"] = "#202120",
      ["surface0"] = "#2C2E2C",
      ["surface1"] = "#2C2E2C",
      ["surface2"] = "#303437",
      ["border"] = "#AAA497",
      ["search"] = "#D6C6DE",
    },
    ["foregrounds"] = {
      ["muted"] = "#AAA497",
      ["comment"] = "#AAA497",
      ["subtext"] = "#AAA497",
      ["text"] = "#BDB7AB",
      ["bright"] = "#BDB7AB",
    },
    ["accents"] = {
      ["olive"] = "#BDB7AB",
      ["sage"] = "#A6C995",
      ["gold"] = "#BDB7AB",
      ["ochre"] = "#C1B0CE",
      ["clay"] = "#9DBDE0",
      ["coral"] = "#E09A9D",
      ["aqua"] = "#83C9BE",
      ["blue"] = "#9DBDE0",
      ["mauve"] = "#C1B0CE",
    },
    ["ansi"] = {
      ["black"] = "#000000",
      ["red"] = "#E09A9D",
      ["green"] = "#A6C995",
      ["yellow"] = "#D0BD91",
      ["blue"] = "#9DBDE0",
      ["magenta"] = "#C1B0CE",
      ["cyan"] = "#83C9BE",
      ["white"] = "#BDB7AB",
      ["brightBlack"] = "#AAA497",
      ["brightRed"] = "#E09A9D",
      ["brightGreen"] = "#A6C995",
      ["brightYellow"] = "#D0BD91",
      ["brightBlue"] = "#9DBDE0",
      ["brightMagenta"] = "#C1B0CE",
      ["brightCyan"] = "#83C9BE",
      ["brightWhite"] = "#BDB7AB",
      ["extendedOchre"] = "#D0BD91",
      ["extendedClay"] = "#E09A9D",
    },
    ["diff"] = {
      ["contextForeground"] = "#BDB7AB",
      ["inlineForeground"] = "#000000",
      ["addForeground"] = "#BDB7AB",
      ["addBackground"] = "#273B31",
      ["addEmphasis"] = "#D8B46A",
      ["deleteForeground"] = "#BDB7AB",
      ["deleteBackground"] = "#402E33",
      ["deleteEmphasis"] = "#D8B46A",
      ["changeForeground"] = "#BDB7AB",
      ["changeBackground"] = "#293847",
      ["changeEmphasis"] = "#D8B46A",
      ["hunkForeground"] = "#BDB7AB",
      ["hunkBackground"] = "#293847",
      ["conflictForeground"] = "#000000",
      ["conflictBackground"] = "#D6C6DE",
    },
  },
  terminal = { "#000000", "#E09A9D", "#A6C995", "#D0BD91", "#9DBDE0", "#C1B0CE", "#83C9BE", "#BDB7AB", "#AAA497", "#E09A9D", "#A6C995", "#D0BD91", "#9DBDE0", "#C1B0CE", "#83C9BE", "#BDB7AB", "#D0BD91", "#E09A9D" },
}
