vim.opt.rtp:prepend(assert(vim.env.KANSO_ROOT,'Set KANSO_ROOT'))
vim.opt.rtp:prepend(vim.fn.getcwd())
require('ithilien').load('dawn')
local function hl(n) return vim.api.nvim_get_hl(0,{name=n,link=false}) end
assert(hl('NeoTreeGitAdded').fg==0x315F46)
assert(hl('NeoTreeGitModified').fg==0x345E77)
assert(hl('NeoTreeGitDeleted').fg==0x8B3037)
assert(hl('NeoTreeGitStaged').fg==0x315F46 and hl('NeoTreeGitStaged').underline)
assert(hl('BufferLineWarningSelected').fg==0x795922)
assert(hl('BlinkCmpLabelMatch').bold and hl('BlinkCmpLabelMatch').fg==0)
assert(hl('BlinkCmpSignatureHelpActiveParameter').bg==0xD6C6DE)
assert(hl('SnacksIndent').fg==0xC9CECB)
assert(hl('SnacksIndentScope').fg==0x505456)
assert(hl('BufferLineBufferSelected').bg==0xDEE0DF)
assert(hl('DiffText').bg==0xD8B46A and not hl('DiffText').bold)
assert(hl('SnacksDashboardDesc').fg==0)
assert(hl('SnacksDashboardIcon').fg==0x345E77)
for _,name in ipairs({'SnacksDashboardFooter','SnacksDashboardSpecial'}) do
 assert(hl(name).fg==0x505456 and not hl(name).bold)
end
print('PASS: plugin semantic mappings and plain diff emphasis')
vim.cmd('qa!')
